Controllers/ConcessionariasController.cs
using Intelectah.Dapper;
using Intelectah.Models;
using Intelectah.Repositorio;
using Intelectah.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Intelectah.Controllers
{
    public class ConcessionariasController : Controller
    {

        private readonly IConcessionariasRepositorio _concessionariasRepositorio;
        private readonly BancoContext _bancoContext;

        public ConcessionariasController(IConcessionariasRepositorio concessionariasRepositorio)
        {
            _concessionariasRepositorio = concessionariasRepositorio;
        }

        public IActionResult Index()
        {
            var concessionarias = _concessionariasRepositorio.BuscarTodos();
            var viewModel = concessionarias.Select(c => new ConcessionariasViewModel
            {
                ConcessionariaID = c.ConcessionariaID,
                Nome = c.Nome,
                Endereco = new EnderecoViewModel
                {
                    EnderecoCompleto = c.EnderecoCompleto,
                    Cidade = c.Cidade,
                    Estado = c.Estado,
                    CEP = c.CEP
                },
                Telefone = c.Telefone,
                Email = c.Email,
                CapacidadeMax = c.CapacidadeMax
            }).ToList();

            return View(viewModel);
        }

        public IActionResult Criar()
        {
            var viewModel = new ConcessionariasViewModel
            {
                Endereco = new EnderecoViewModel()
            };

            ViewData["FormAction"] = "Criar";
            return View(viewModel);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            var concessionaria = _concessionariasRepositorio.ListarPorId(id);

            if (concessionaria == null)
            {
                TempData["MensagemErro"] = "Concessionária não encontrada.";
                return RedirectToAction("Index");
            }

            var viewModel = new ConcessionariasViewModel
            {
                ConcessionariaID = concessionaria.ConcessionariaID,
                Nome = concessionaria.Nome,
                Endereco = new EnderecoViewModel
                {
                    EnderecoCompleto = concessionaria.EnderecoCompleto,
                    Cidade = concessionaria.Cidade,
                    Estado = concessionaria.Estado,
                    CEP = concessionaria.CEP
                },
                Telefone = concessionaria.Telefone,
                Email = concessionaria.Email,
                CapacidadeMax = concessionaria.CapacidadeMax
            };

            return View(viewModel);
        }

        public IActionResult Editar(int id)
        {
            var concessionaria = _concessionariasRepositorio.ListarPorId(id);

            if (concessionaria == null)
            {
                TempData["MensagemErro"] = "Concessionária não encontrada.";
                return RedirectToAction("Index");
            }

            var viewModel = new ConcessionariasViewModel
            {
                ConcessionariaID = concessionaria.ConcessionariaID,
                Nome = concessionaria.Nome,
                Endereco = new EnderecoViewModel
                {
                    EnderecoCompleto = concessionaria.EnderecoCompleto,
                    Cidade = concessionaria.Cidade,
                    Estado = concessionaria.Estado,
                    CEP = concessionaria.CEP
                },
                Telefone = concessionaria.Telefone,
                Email = concessionaria.Email,
                CapacidadeMax = concessionaria.CapacidadeMax
            };

            ViewData["FormAction"] = "Editar";
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Criar(ConcessionariasViewModel viewModel)
        {
            if (viewModel.Nome.Length > 100)
            {
                ModelState.AddModelError(nameof(viewModel.Nome), "O nome da concessionária não pode exceder 100 caracteres.");
            }

            if (!_concessionariasRepositorio.VerificarNomeConcessionariaUnico(viewModel.Nome))
            {
                ModelState.AddModelError(nameof(viewModel.Nome), "O nome da concessionária já existe.");
            }

            if (ModelState.IsValid)
            {
                var concessionaria = new ConcessionariasModel
                {
                    Nome = viewModel.Nome,
                    EnderecoCompleto = viewModel.Endereco.EnderecoCompleto,
                    Cidade = viewModel.Endereco.Cidade,
                    Estado = viewModel.Endereco.Estado,
                    CEP = viewModel.Endereco.CEP,
                    Telefone = viewModel.Telefone,
                    Email = viewModel.Email,
                    CapacidadeMax = viewModel.CapacidadeMax
                };

                _concessionariasRepositorio.Adicionar(concessionaria);
                TempData["MensagemSucesso"] = "Concessionária cadastrada com sucesso!";
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Editar(ConcessionariasViewModel viewModel)
        {
            if (viewModel.Nome.Length > 100)
            {
                ModelState.AddModelError(nameof(viewModel.Nome), "O nome da concessionária não pode exceder 100 caracteres.");
            }

            if (ModelState.IsValid)
            {
             
                var concessionaria = new ConcessionariasModel
                {
                    ConcessionariaID = viewModel.ConcessionariaID,
                    Nome = viewModel.Nome,
                    EnderecoCompleto = viewModel.Endereco.EnderecoCompleto,
                    Cidade = viewModel.Endereco.Cidade,
                    Estado = viewModel.Endereco.Estado,
                    CEP = viewModel.Endereco.CEP,
                    Telefone = viewModel.Telefone,
                    Email = viewModel.Email,
                    CapacidadeMax = viewModel.CapacidadeMax
                };

                _concessionariasRepositorio.Atualizar(concessionaria);
                TempData["MensagemSucesso"] = "Concessionária atualizada com sucesso!";
                return RedirectToAction("Index");
            }

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _concessionariasRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Concessionária deletada com sucesso.";
                }
                else
                {
                    TempData["MensagemErro"] = "Não foi possível deletar a concessionária.";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possível deletar a concessionária, tente novamente. Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Concessionarias/ApagarConfirmacao.cshtml
@model Intelectah.ViewModel.ConcessionariasViewModel

@{
    ViewData["Title"] = "Confirmar Exclusão";
}

<h1>@ViewData["Title"]</h1>

<p>Você tem certeza de que deseja excluir a concessionária "@Model.Nome"?</p>

<div>
    <form asp-action="Apagar" method="post">
        <input type="hidden" name="id" asp-for="ConcessionariaID" />
        <button type="submit" class="btn btn-danger">Excluir</button>
        <a asp-action="Index" class="btn btn-secondary">Cancelar</a>
    </form>
</div>

Views/Concessionarias/Criar.cshtml
@model Intelectah.ViewModel.ConcessionariasViewModel

@{
    ViewData["Title"] = "Criar Concessionária";
    ViewData["FormAction"] = "Criar";
}

<h1>Criar Concessionária</h1>

<form asp-action="@ViewData["FormAction"]" method="post">
    @Html.AntiForgeryToken()
    @Html.Partial("Forms", Model)

    <div class="form-group">
        <button type="submit" class="btn btn-primary" style="margin-top:10px">Salvar</button>
        <a asp-action="Index" class="btn btn-secondary" style="margin-top:10px">Cancelar</a>
    </div>
</form>

Views/Concessionarias/Editar.cshtml
@model Intelectah.ViewModel.ConcessionariasViewModel

@{
    ViewData["Title"] = "Editar Concessionária";
    ViewData["FormAction"] = "Editar";
}

<h1>Editar Concessionária</h1>

<form asp-action="@ViewData["FormAction"]" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="ConcessionariaID" />

    @Html.Partial("Forms", Model)

    <div class="form-group">
        <button type="submit" class="btn btn-primary" style="margin-top:10px">Editar</button>
        <a asp-action="Index" class="btn btn-secondary" style="margin-top:10px">Cancelar</a>
    </div>
</form>

Views/Concessionarias/Forms.cshtml
@model Intelectah.ViewModel.ConcessionariasViewModel

<div class="form-group col-md-6">
    <label asp-for="Nome" class="control-label">Concessionária</label>
    <input asp-for="Nome" class="form-control" placeholder="Nome da concessionária" />
    <span asp-validation-for="Nome" class="text-danger"></span>
</div>

<div class="form-group col-md-6">
    <label asp-for="Endereco.EnderecoCompleto" class="control-label">Endereço</label>
    <input asp-for="Endereco.EnderecoCompleto" class="form-control" placeholder="Informe a Rua/AV" />
    <span asp-validation-for="Endereco.EnderecoCompleto" class="text-danger"></span>
</div>

<div class="form-group col-md-6">
    <label asp-for="Endereco.Cidade" class="control-label">Cidade</label>
    <input asp-for="Endereco.Cidade" class="form-control" placeholder="Informe o nome da cidade" />
    <span asp-validation-for="Endereco.Cidade" class="text-danger"></span>
</div>

<div class="form-group col-md-6">
    <label asp-for="Endereco.Estado" class="control-label">Estado</label>
    <input asp-for="Endereco.Estado" class="form-control" placeholder="Informe o estado" />
    <span asp-validation-for="Endereco.Estado" class="text-danger"></span>
</div>

<div class="form-group col-md-6">
    <label asp-for="Endereco.CEP" class="control-label">CEP</label>
    <input asp-for="Endereco.CEP" class="form-control" placeholder="Informe o CEP" id="cep" />
    <span asp-validation-for="Endereco.CEP" class="text-danger"></span>
</div>

<div class="form-group col-md-6">
    <label asp-for="Telefone" class="control-label">Telefone</label>
    <input asp-for="Telefone" class="form-control" placeholder="Informe o telefone" id="telefone"/>
    <span asp-validation-for="Telefone" class="text-danger"></span>
</div>

<div class="form-group col-md-6">
    <label asp-for="Email" class="control-label">Email</label>
    <input asp-for="Email" class="form-control" placeholder="Informe o email" />
    <span asp-validation-for="Email" class="text-danger"></span>
</div>

<div class="form-group col-md-6">
    <label asp-for="CapacidadeMax" class="control-label">Capacidade máxima de veículos</label>
    <input asp-for="CapacidadeMax" class="form-control" />
    <span asp-validation-for="CapacidadeMax" class="text-danger"></span>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/inputmask/5.0.8/inputmask.min.js"></script>
<script src="~/js/fabricantes.js"></script>

Views/Concessionarias/Index.cshtml
@model IEnumerable<Intelectah.ViewModel.ConcessionariasViewModel>


@{
    ViewData["Title"] = "Concessionárias";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Concessionarias" asp-action="Criar">Adicionar nova concessionária</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <h1 class="display-4">Lista de Concessionárias</h1>
    <table class="table text-center" id="tabela-concessionarias">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Nome</th>
                <th scope="col">Endereço Completo</th>
                <th scope="col">Cidade</th>
                <th scope="col">Estado</th>
                <th scope="col">CEP</th>
                <th scope="col">Telefone</th>
                <th scope="col">E-mail</th>
                <th scope="col">Capacidade Máxima de Veículos</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var concessionaria in Model)
            {
                <tr>
                    <td></td>
                    <td>@concessionaria.Nome</td>
                    <td>@concessionaria.Endereco.EnderecoCompleto</td>
                    <td>@concessionaria.Endereco.Cidade</td>
                    <td>@concessionaria.Endereco.Estado</td>
                    <td>@concessionaria.Endereco.CEP</td>
                    <td>@concessionaria.Telefone</td>
                    <td>@concessionaria.Email</td>
                    <td>@concessionaria.CapacidadeMax</td>
                    <td>
                        <a role="button" class="btn btn-primary" asp-route-id="@concessionaria.ConcessionariaID" asp-controller="Concessionarias" asp-action="Editar">Editar</a>
                    </td>
                    <td>
                        <a role="button" class="btn btn-danger" asp-route-id="@concessionaria.ConcessionariaID" asp-controller="Concessionarias" asp-action="ApagarConfirmacao">Apagar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>