Controllers/VeiculosController.cs
using Intelectah.Enums;
using Intelectah.Models;
using Intelectah.Repositorio;
using Intelectah.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Intelectah.Controllers
{
    public class VeiculosController : Controller
    {
        private readonly IVeiculosRepositorio _veiculosRepositorio;
        private readonly IFabricantesRepositorio _fabricantesRepositorio;

        public VeiculosController(IVeiculosRepositorio veiculosRepositorio, IFabricantesRepositorio fabricantesRepositorio)
        {
            _veiculosRepositorio = veiculosRepositorio;
            _fabricantesRepositorio = fabricantesRepositorio;
        }

        public IActionResult Index()
        {
            var veiculos = _veiculosRepositorio.BuscarTodos();
            var fabricantes = _fabricantesRepositorio.BuscarTodos();

            var veiculosViewModel = veiculos.Select(v => new VeiculosViewModel
            {
                VeiculoID = v.VeiculoID,
                ModeloVeiculo = v.ModeloVeiculo,
                AnoFabricacao = v.AnoFabricacao,
                ValorVeiculo = v.ValorVeiculo,
                FabricanteID = v.FabricanteID,
                Tipo = v.Tipo,
                Descricao = v.Descricao,
                Fabricantes = fabricantes.Select(f => new SelectListItem
                {
                    Value = f.FabricanteID.ToString(),
                    Text = f.NomeFabricante
                }).ToList()
            }).ToList();

            return View(veiculosViewModel);
        }

        public IActionResult Criar()
        {
            var fabricantes = _fabricantesRepositorio.BuscarTodos();

            var viewModel = new VeiculosViewModel
            {
                Fabricantes = fabricantes.Select(f => new SelectListItem
                {
                    Value = f.FabricanteID.ToString(),
                    Text = f.NomeFabricante
                }).ToList(),
                TiposVeiculos = Enum.GetValues(typeof(TipoVeiculo))
                    .Cast<TipoVeiculo>()
                    .Select(t => new SelectListItem
                    {
                        Value = t.ToString(),
                        Text = t.ToString()
                    })
                    .ToList()
            };

            return View(viewModel);
        }

        public IActionResult Editar(int id)
        {
            var veiculo = _veiculosRepositorio.ListarPorId(id);
            if (veiculo == null)
            {
                return NotFound();
            }

            var fabricantes = _fabricantesRepositorio.BuscarTodos();

            var viewModel = new VeiculosViewModel
            {
                VeiculoID = veiculo.VeiculoID,
                ModeloVeiculo = veiculo.ModeloVeiculo,
                AnoFabricacao = veiculo.AnoFabricacao,
                ValorVeiculo = veiculo.ValorVeiculo,
                FabricanteID = veiculo.FabricanteID,
                Tipo = veiculo.Tipo,
                Descricao = veiculo.Descricao,

                Fabricantes = fabricantes.Select(f => new SelectListItem
                {
                    Value = f.FabricanteID.ToString(),
                    Text = f.NomeFabricante
                }).ToList(),

                TiposVeiculos = Enum.GetValues(typeof(TipoVeiculo))
                    .Cast<TipoVeiculo>()
                    .Select(t => new SelectListItem
                    {
                        Value = t.ToString(),
                        Text = t.ToString()
                    })
                    .ToList()
            };

            return View(viewModel);
        }
        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _veiculosRepositorio.Apagar(id);
                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Veículo deletado com sucesso";
                }
                else
                {
                    TempData["MensagemErro"] = "Não foi possível deletar o veículo.";
                }
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Não foi possível deletar o veículo, tente novamente. Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> ApagarConfirmacao(int id)
        {
            var veiculo = _veiculosRepositorio.ListarPorId(id);
            if (veiculo == null)
            {
                TempData["MensagemErro"] = "Veículo não encontrado.";
                return RedirectToAction("Index");
            }

            var viewModel = new VeiculosViewModel
            {
                VeiculoID = veiculo.VeiculoID,
                ModeloVeiculo = veiculo.ModeloVeiculo,
                AnoFabricacao = veiculo.AnoFabricacao,
                ValorVeiculo = veiculo.ValorVeiculo,
                FabricanteID = veiculo.FabricanteID,
                Tipo = veiculo.Tipo
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Criar(VeiculosViewModel viewModel)
        {
            if (viewModel.ModeloVeiculo.Length > 100)
            {
                ModelState.AddModelError(nameof(viewModel.ModeloVeiculo), "O modelo do veículo não pode exceder 100 caracteres.");
            }
            if (viewModel.AnoFabricacao > DateTime.Now.Year)
            {
                ModelState.AddModelError(nameof(viewModel.AnoFabricacao), "O ano de fabricação não pode ser no futuro.");
            }

            if (ModelState.IsValid)
            {
                var veiculo = new VeiculosModel
                {
                    VeiculoID = viewModel.VeiculoID,
                    ModeloVeiculo = viewModel.ModeloVeiculo,
                    AnoFabricacao = viewModel.AnoFabricacao,
                    ValorVeiculo = viewModel.ValorVeiculo,
                    FabricanteID = viewModel.FabricanteID,
                    Tipo = viewModel.Tipo,
                    Descricao = viewModel.Descricao
                };

                _veiculosRepositorio.Adicionar(veiculo);
                TempData["MensagemSucesso"] = "Veículo cadastrado com sucesso";
                return RedirectToAction("Index");
            }

            var fabricantes = _fabricantesRepositorio.BuscarTodos();
            viewModel.Fabricantes = fabricantes.Select(f => new SelectListItem
            {
                Value = f.FabricanteID.ToString(),
                Text = f.NomeFabricante
            }).ToList();

            viewModel.TiposVeiculos = Enum.GetValues(typeof(TipoVeiculo))
                .Cast<TipoVeiculo>()
                .Select(t => new SelectListItem
                {
                    Value = t.ToString(),
                    Text = t.ToString()
                })
                .ToList();

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Editar(VeiculosViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var veiculo = new VeiculosModel
                {
                    VeiculoID = viewModel.VeiculoID,
                    ModeloVeiculo = viewModel.ModeloVeiculo,
                    AnoFabricacao = viewModel.AnoFabricacao,
                    ValorVeiculo = viewModel.ValorVeiculo,
                    FabricanteID = viewModel.FabricanteID,
                    Tipo = viewModel.Tipo,
                    Descricao = viewModel.Descricao,
                };

                _veiculosRepositorio.Atualizar(veiculo);
                TempData["MensagemSucesso"] = "Veículo alterado com sucesso";
                return RedirectToAction("Index");
            }

            var fabricantes = _fabricantesRepositorio.BuscarTodos();
            viewModel.Fabricantes = fabricantes.Select(f => new SelectListItem
            {
                Value = f.FabricanteID.ToString(),
                Text = f.NomeFabricante
            }).ToList();

            viewModel.TiposVeiculos = Enum.GetValues(typeof(TipoVeiculo))
                .Cast<TipoVeiculo>()
                .Select(t => new SelectListItem
                {
                    Value = t.ToString(),
                    Text = t.ToString()
                })
                .ToList();

            return View(viewModel);
        }       
    }
}

Views/Veiculos/ApagarConfirmacao.cshtml
@model Intelectah.ViewModel.VeiculosViewModel

@{
    ViewData["Title"] = "Confirmação para apagar o veículo";
}

<form method="post" asp-controller="Veiculos" asp-action="Apagar">
    <input type="hidden" name="Id" value="@Model.VeiculoID" />
    <div class="text-center">
        <h3>Realmente deseja apagar o veículo? @Model.ModeloVeiculo</h3>
    </div>
    <a class="btn btn-primary" role="button" asp-controller="Veiculos" asp-action="Index">Cancelar exclusão</a>
    <button type="submit" class="btn btn-danger">Confirmar exclusão</button>
</form>

Views/Veiculos/Criar.cshtml
@model Intelectah.ViewModel.VeiculosViewModel
@using Microsoft.AspNetCore.Mvc.Rendering

@{
    ViewData["Title"] = "Adicionar veículo";
}

<div class="text-center">
    <h1 class="display-4">Adicionar veículo</h1>
</div>

<form asp-controller="Veiculos" asp-action="Criar" method="post">
    @Html.Partial("Forms")
    <div class="form-group">
        <button type="submit" class="btn btn-primary" style="margin-top:10px">Salvar</button>
        <a asp-action="Index" class="btn btn-secondary" style="margin-top:10px">Cancelar</a>
    </div>
</form>

Views/Veiculos/Editar.cshtml
@model Intelectah.ViewModel.VeiculosViewModel

@{
    ViewData["Title"] = "Editar veículo";
}


<div class="text-center">

    <h1 class="display-4">Editar veículo</h1>

</div>

<form asp-controller="Veiculos" asp-action="Editar" method="post">
    <input type="hidden" asp-for="VeiculoID" />
    @Html.Partial("Forms.cshtml")

    <div class="form-group">
        <button type="submit" class="btn btn-primary" style="margin-top:10px">Salvar</button>
        <a asp-action="Index" class="btn btn-secondary" style="margin-top:10px">Cancelar</a>
    </div>
</form>

Views/Veiculos/Forms.cshtml
@model Intelectah.ViewModel.VeiculosViewModel

<div class="form-row">
    <div class="form-group col-md-6">
        <label asp-for="ModeloVeiculo" class="control-label">Modelo do veículo</label>
        <input asp-for="ModeloVeiculo" class="form-control" />
        <span asp-validation-for="ModeloVeiculo" class="text-danger"></span>
    </div>

    <div class="form-group col-md-6">
        <label asp-for="AnoFabricacao" class="control-label">Ano de fabricação</label>
        <input asp-for="AnoFabricacao" class="form-control" />
        <span asp-validation-for="AnoFabricacao" class="text-danger"></span>
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-6">
        <label asp-for="ValorVeiculo" class="control-label">Valor do veículo</label>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">R$</span>
            </div>
            <input asp-for="ValorVeiculo" class="form-control" />
        </div>
        <span asp-validation-for="ValorVeiculo" class="text-danger"></span>
    </div>

    <div class="form-group col-md-6">
        <label asp-for="FabricanteID" class="control-label">Fabricante</label>
        <select asp-for="FabricanteID" class="form-control">
            <option value="">Selecione um fabricante</option>
            @foreach (var fabricante in Model.Fabricantes)
            {
                <option value="@fabricante.Value">@fabricante.Text</option>
            }
        </select>
        <span asp-validation-for="FabricanteID" class="text-danger"></span>
    </div>
</div>

<div class="form-row">
    <div class="form-group col-md-6">
        <label asp-for="Tipo" class="control-label">Tipo de veículo</label>
        <select asp-for="Tipo" asp-items="Model.TiposVeiculos" class="form-control"></select>
        <span asp-validation-for="Tipo" class="text-danger"></span>
    </div>


    <div class="form-group col-md-6">
        <label asp-for="Descricao" class="control-label">Descrição do veículo</label>
        <textarea asp-for="Descricao" class="form-control"></textarea>
        <span asp-validation-for="Descricao" class="text-danger"></span>
    </div>
</div>

Views/Veiculos/Index.cshtml
@model IEnumerable<Intelectah.ViewModel.VeiculosViewModel>

@{
    ViewData["Title"] = "Veiculos";
}


<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Veiculos" asp-action="Criar">Adicionar novo veículo</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">

            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <b />

    <h1 class="display-4">Lista de veículos</h1>
    <form>
        <table class="table text-center" id="tabela-veiculos">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Modelo</th>
                    <th scope="col">Ano de fabricação</th>
                    <th scope="col">R$</th>
                    <th scope="col">Fabricante</th>
                    <th scope="col">Tipo de veículo</th>
                    <th scope="col">Descrição</th>
                    <th scope="col"></th>

                </tr>
            </thead>
            <tbody>
                @if (Model != null && Model.Any())
                {
                    foreach (var veiculo in Model)
                    {
                        <tr>
                            <td></td>
                            <td>@veiculo.ModeloVeiculo</td>
                            <td>@veiculo.AnoFabricacao</td>
                            <td>@veiculo.ValorVeiculo</td>
                            <td>
                                @veiculo.Fabricantes.FirstOrDefault(f => f.Value == veiculo.FabricanteID.ToString())?.Text
                            </td>
                            <td>@veiculo.Tipo</td>
                            <td>@veiculo.Descricao</td>
                            <td>
                                <div class="btn-group" role="group">
                                    <a role="button" class="btn btn-primary" asp-route-id="@veiculo.VeiculoID" asp-controller="Veiculos" asp-action="Editar">Editar</a>
                                    <a role="button" class="btn btn-danger" asp-route-id="@veiculo.VeiculoID" asp-controller="Veiculos" asp-action="ApagarConfirmacao">Apagar</a>
                                </div>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </form>
</div>